language: python
services: postgresql
python:
- '2.7'
addons:
- postgresql: '9.1'
before_install:
- openssl aes-256-cbc -K $encrypted_2de2aeba0202_key -iv $encrypted_2de2aeba0202_iv -in .private/private_data.tar.enc -out private_data.tar -d
install:
- pip install kamaki==0.13.5
- pip install paramiko
- pip install ansible==1.9.2
- pip install django==1.7.10
- pip install djorm-pgarray==1.2
- pip install psycopg2==2.5.4
- pip install djangorestframework==2.4.3
- pip install rest_framework_ember==1.3.2
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- pip install requests
- pip install celery==3.1.17
- pip install django-celery==3.1.16
- pip install django-admin-bootstrapped==2.4.0
- sudo apt-get update
- sudo apt-get install sshpass
- sudo apt-get install shunit2
before_script:
- psql -c 'create user developer with createdb;' -U postgres
- psql -c 'create database escience with owner developer;' -U postgres
- tar -xvf private_data.tar
- python webapp/manage.py syncdb --noinput
- cd orka
- python setup.py install
- cd ..
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
- ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
script:
- nosetests -v tests/test_create_cluster.py
- bash tests/integration/test_integration_hdpbase.sh
- bash tests/integration/test_integration_hue.sh
- bash tests/integration/test_integration_ecosystem.sh
- bash tests/integration/test_integration_cdh.sh
- bash tests/integration/test_integration_vre_server.sh
