language: python
services: postgresql
python:
- '2.7'
addons:
- postgresql: '9.1'
before_install:
- openssl aes-256-cbc -K $encrypted_7dca1dac1171_key -iv $encrypted_7dca1dac1171_iv
  -in .private/.config.txt.enc -out .private/.config.txt -d
install:
- pip install kamaki==0.13.1
- pip install paramiko
- pip install ansible==1.9.2
- pip install django
- pip install djorm-pgarray
- pip install psycopg2
- pip install djangorestframework
- pip install rest_framework_ember
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- pip install requests
- pip install django-celery
- sudo apt-get install sshpass
- sudo apt-get install shunit2
before_script:
- psql -c 'create user developer with createdb;' -U postgres
- psql -c 'create database escience with owner developer;' -U postgres
- python webapp/manage.py syncdb --noinput
- cd orka
- python setup.py install
- cd ..
- npm install testem -g
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
script:
- nosetests -sv tests/test_create_cluster.py
- bash tests/integration/test_integration_hdpbase.sh
- bash tests/integration/test_integration_hue.sh
- bash tests/integration/test_integration_ecosystem.sh
- bash tests/integration/test_integration_cdh.sh
- bash tests/integration/test_integration_drupal.sh
