---
 # PostgreSql variables
 db_user: orka_admin
 db_password: escience
 db_name: escience
 db_host: 127.0.0.1
 choose_role: webserver

 # setup_orka_admin variables
 orka_admin_password: $1$SomeSalt$W98.5N4Mc2EpxOTlI9MI20
 create_orka_admin: False
 # Django admin variables
 django_admin_name: orka_admin
 django_admin_email: orka@example.com
 django_admin_password: esc1ence@2015
 ansible_sudo_pass: lalakia
 # rabbitmquser orkarbmq
 # rabbitmq password=orkapass
 path_to_pref: roles/webserver/files/my_preferences
 path_to_sources_list: roles/webserver/files/sources.list

 # Django project variables
 user_home: /home/orka_admin
 my_project_dir: "{{user_home}}/projects"
 my_project_name: e-science
 webapp_dir: webapp
 settings_path: "{{my_project_dir}}/{{my_project_name}}/{{webapp_dir}}/backend"
 path_to_java_dirs: "{{my_project_dir}}/{{my_project_name}}/pithosfs/java"
 orka_version: orka-0.2
 orka_db_sql_script: backend_insert_tables.sql
 local_encrypt_file_path: "../{{webapp_dir}}/backend/encrypt_key.py" 
 remote_encrypt_file_path: "{{settings_path}}/encrypt_key.py"
 # Paths for project
 project_path: "{{my_project_dir}}/{{my_project_name}}"
 # Openssl variables
 certificate_key_lifetime: 3650
 key_rsa: 2048
 