---
 # PostgreSql constants
 db_host: 127.0.0.1
 db_user: orka_admin
 db_name: escience
 choose_role: webserver
 django_admin_name: orka_admin
 django_admin_email: orka@example.com
 escience_repo: https://github.com/ioannisstenos/e-science.git
 escience_version: develop

 # setup_orka_admin variables
 create_orka_admin: False
 path_to_pref: roles/webserver/files/my_preferences
 path_to_sources_list: roles/webserver/files/sources.list

 # Django project variables
 user_home: /home/orka_admin
 my_project_dir: "{{user_home}}/projects"
 my_project_name: e-science
 webapp_dir: webapp
 settings_path: "{{my_project_dir}}/{{my_project_name}}/{{webapp_dir}}/backend"
 path_to_java_dirs: "{{my_project_dir}}/{{my_project_name}}/pithosfs/java"
 orka_version: orka-0.2
 orka_db_sql_script: backend_insert_tables.sql
 local_encrypt_file_path: "../{{webapp_dir}}/backend/encrypt_key.py" 
 remote_encrypt_file_path: "{{settings_path}}/encrypt_key.py"
 # Paths for project
 project_path: "{{my_project_dir}}/{{my_project_name}}"
 # Openssl variables
 certificate_key_lifetime: 3650
 key_rsa: 2048
