---
  - name: clean master temp storage dir
    tags: format
    shell: sudo -u hdfs rm -rf /data/1/dfs/nn/* /nfsmount/dfs/nn/*
    when: is_master

  - name: clean slaves temp storage dir
    tags: format
    shell: sudo -u hdfs rm -rf /data/1/dfs/dn/* /data/2/dfs/dn/* /data/3/dfs/dn/* /data/4/dfs/dn/*
    when: is_slave

  - name: format hdfs
    tags: format
    command: sudo -u hdfs hdfs namenode -format -force chdir={{ cloudera_bin }}
    when: is_master

  - name: start Namenode and Resource Manager
    tags: start
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hadoop-hdfs-namenode', state: 'restarted' }
      - { name: 'hadoop-yarn-resourcemanager',  state: 'restarted' }
    when: is_master

  - name: start Datanode and Node Manager
    tags: start
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hadoop-hdfs-datanode', state: 'restarted' }
      - { name: 'hadoop-yarn-nodemanager',  state: 'restarted' }
    when: is_slave

  - name: Create mandatory directories in Hdfs
    tags: CLOUDstart
    action: command {{item}} chdir={{ cloudera_bin }}
    with_items:
      - sudo -u hdfs hadoop fs -mkdir -p /user
      - sudo -u hdfs hadoop fs -mkdir -p /user/yarn
      - sudo -u hdfs hadoop fs -chown yarn /user/yarn
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/yarn
      - sudo -u hdfs hadoop fs -mkdir -p /user/root
      - sudo -u hdfs hadoop fs -chown root /user/root
      - sudo -u hdfs hadoop fs -mkdir -p /user/mapred
      - sudo -u hdfs hadoop fs -chown mapred /user/mapred
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/mapred
      - sudo -u hdfs hadoop fs -mkdir -p /user/hdfs
      - sudo -u hdfs hadoop fs -chown hdfs /user/hdfs
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/hdfs
      - sudo -u hdfs hadoop fs -mkdir -p /user/flume
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/flume
      - sudo -u hdfs hadoop fs -chown flume:flume /user/flume
      - sudo -u hdfs hadoop fs -mkdir -p /tmp
      - sudo -u hdfs hadoop fs -chmod -R 1777 /tmp
      - sudo -u hdfs hadoop fs -mkdir -p /user/history
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/history
      - sudo -u hdfs hadoop fs -chown mapred:hadoop /user/history
      - sudo -u hdfs hadoop fs -mkdir -p /var/log/hadoop-yarn
      - sudo -u hdfs hadoop fs -chown yarn:mapred /var/log/hadoop-yarn
      - sudo -u hdfs hadoop fs -mkdir -p /user/spark/applicationHistory
      - sudo -u hdfs hadoop fs -chown -R spark:spark /user/spark
      - sudo -u hdfs hadoop fs -chmod 1777 /user/spark/applicationHistory
      - sudo -u hdfs hadoop fs -mkdir -p /user/hive/warehouse
      - sudo -u hdfs hadoop fs -chmod 1777 /user/hive/warehouse
      - sudo -u hdfs hadoop fs -mkdir -p /user/oozie
      - sudo -u hdfs hadoop fs -chmod -R 1777 /user/oozie
      - sudo -u hdfs hadoop fs -chown oozie:oozie /user/oozie
      - sudo -u hdfs hadoop fs -mkdir -p /var/log/oozie
      - sudo -u hdfs hadoop fs -chown oozie:oozie /var/log/oozie
      - sudo -u hdfs hadoop fs -mkdir -p /hbase
      - sudo -u hdfs hadoop fs -chown hbase /hbase
    when: is_master

  - name: start History Server
    tags: CLOUDstart
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hadoop-mapreduce-historyserver', state: 'restarted' }
    when: is_master

  - name: Stop Flume
    tags: stop
    service: name=flume-ng-agent state=stopped
    when: is_master

  - name: stop Namenode, Resource Manager and History Server
    tags: stop
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hadoop-hdfs-namenode', state: 'stopped' }
      - { name: 'hadoop-yarn-resourcemanager',  state: 'stopped' }
      - { name: 'hadoop-mapreduce-historyserver', state: 'stopped' }
    when: is_master

  - name: stop Datanode and Node Manager
    tags: stop
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hadoop-hdfs-datanode', state: 'stopped' }
      - { name: 'hadoop-yarn-nodemanager',  state: 'stopped' }
    when: is_slave

  - name: Copy oozie sharelib
    tags: CLOUDstart
    shell: oozie-setup sharelib create -fs hdfs://{{hostvars[groups['master_cloud'][0]].inventory_hostname_short}}:9000 -locallib /usr/lib/oozie/oozie-sharelib-yarn
    when: is_master

  - name: start Flume,Hbase,Spark,Oozie,Hive and Hue in Cloudera cluster
    tags: CLOUDstart
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'flume-ng-agent', state: 'restarted' }
      - { name: 'zookeeper-server', state: 'restarted' }
      - { name: 'hbase-master', state: 'restarted' }
      - { name: 'hbase-thrift', state: 'restarted' }
      - { name: 'hbase-rest', state: 'restarted' }
      - { name: 'hbase-regionserver', state: 'restarted' }
      - { name: 'spark-master', state: 'restarted' }
      - { name: 'spark-history-server', state: 'restarted' }
      - { name: 'hive-metastore', state: 'restarted' }
      - { name: 'hive-server2', state: 'restarted' }
      - { name: 'oozie', state: 'restarted' }
      - { name: 'livy-server', state: 'started' }
      - { name: 'hue', state: 'restarted' }
    when: is_master

  - name: start Hbase regionservers and spark workers in cloudera cluster
    tags: CLOUDstart
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'spark-worker', state: 'restarted' }
      - { name: 'hbase-regionserver', state: 'restarted' }
    when: is_slave

  - name: stop Hbase,spark,oozie,hive and hue in cloudera cluster
    tags: CLOUDstop
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'hue', state: 'stopped' }
      - { name: 'oozie', state: 'stopped' }
      - { name: 'hive-metastore', state: 'stopped' }
      - { name: 'hive-server2', state: 'stopped' }
      - { name: 'hbase-master', state: 'stopped' }
      - { name: 'hbase-thrift', state: 'stopped' }
      - { name: 'hbase-rest', state: 'stopped' }
      - { name: 'hbase-regionserver', state: 'stopped' }
      - { name: 'spark-master', state: 'stopped' }
      - { name: 'spark-history-server', state: 'stopped' }
      - { name: 'zookeeper-server', state: 'stopped' }
    when: is_master

  - name: stop Hbase regionservers and spark workers in cloudera cluster
    tags: CLOUDstop
    service: "name={{item.name}} state={{item.state}}"
    with_items:
      - { name: 'spark-worker', state: 'stopped' }
      - { name: 'hbase-regionserver', state: 'stopped' }
    when: is_slave

  - name: Stop Livy Server
    tags: CLOUDstop
    shell: if pgrep livy; then pkill livy; fi
    when: is_master