---
  - name: clean namenode and datanodes temp storage dir
    tags: format
    shell: sudo -u hduser rm -rf /app/hadoop/tmp/*

  - name: format hdfs
    tags: format
    command: sudo -u hduser ./hdfs namenode -format -force chdir={{hadoop_home}}/bin
    when: is_master

  - name: start dfs
    tags: start
    command: sudo -u hduser ./start-dfs.sh chdir={{hadoop_home}}/sbin
    when: is_master

  - name: start yarn
    tags: start
    command: sudo -u hduser ./start-yarn.sh chdir={{hadoop_home}}/sbin
    when: is_master

  - name: start history server
    tags: start
    command: sudo -u hduser ./mr-jobhistory-daemon.sh start historyserver chdir={{hadoop_home}}/sbin
    when: is_master

  - name: Creates directory
    tags: start
    action: command sudo -u hduser ./hadoop fs -mkdir -p /user/hduser/flume chdir={{hadoop_home}}/bin
    when: is_master

  - name: Chmod to hduser directory
    tags: start
    action: command sudo -u hduser ./hadoop fs -chmod 1777 /user/hduser chdir={{hadoop_home}}/bin
    when: is_master

  - name: Enable flume-agent to run by default
    tags: FLUMEstart
    command: systemctl start flume-agent
    when: is_master

  - name: Start Flume
    tags: FLUMEstart
    service: name=flume-agent state=restarted
    when: is_master

  - name: Start Hue
    tags: HUEstart
    command: sudo -u hduser ./supervisor -d chdir=/usr/local/hue/build/env/bin/
    when: is_master

  - name: Create Hive and oozie directories
    tags: ECOSYSTEMstart
    action: command {{item}} chdir={{hadoop_home}}/bin
    with_items:
      - sudo -u hduser ./hadoop fs -mkdir -p /user/root
      - sudo -u hduser ./hadoop fs -chown -R root:supergroup /user/root
      - sudo -u hduser ./hadoop fs -chmod 1777 /user/root
      - sudo -u hduser ./hadoop fs -mkdir -p /user/oozie
      - sudo -u hduser ./hadoop fs -chmod 1777 /user/oozie
      - sudo -u hduser ./hadoop fs -mkdir -p /tmp
      - sudo -u hduser ./hadoop fs -mkdir -p /user/hive/warehouse
      - sudo -u hduser ./hadoop fs -chmod g+w /user/hive/warehouse
      - sudo -u hduser ./hadoop fs -chmod g+w /tmp
    when: is_master

  - name: Create Sharelib Directory on HDFS
    tags: ECOSYSTEMstart
    command: sudo -u hduser /usr/local/oozie/bin/./oozie-setup.sh sharelib create -fs hdfs://{{ hostvars[groups['master'][0]].inventory_hostname_short }}:9000 chdir={{hadoop_home}}/bin
    when: is_master

  - name: Start spark master and slaves
    tags: ECOSYSTEMstart
    shell: ./start-all.sh chdir=/usr/local/spark/sbin/
    when: is_master

  - name: Start Hadoop Ecosystem Servers
    tags: ECOSYSTEMstart
    shell: systemctl start {{item}}
    with_items:
      - hiveserver2
      - livyserver
      - hbaseserver
      - oozieserver
    when: is_master

  - name: Stop Hadoop Ecosystem Servers
    tags: ECOSYSTEMstop
    shell: systemctl stop {{item}}
    with_items:
      - hiveserver2
      - livyserver
      - hbaseserver
      - oozieserver
    when: is_master

  - name: Stop spark master and slaves
    tags: ECOSYSTEMstop
    shell: ./stop-all.sh chdir=/usr/local/spark/sbin/
    when: is_master

  - name: Stop Hue
    tags: HUEstop
    shell: if pgrep supervisor; then pkill supervisor; fi
    when: is_master

  - name: Stop Flume
    tags: FLUMEstop
    service: name=flume-agent state=stopped
    when: is_master

  - name: Stop dfs
    tags: stop
    command: sudo -u hduser ./stop-dfs.sh chdir={{hadoop_home}}/sbin
    when: is_master

  - name: Stop yarn
    tags: stop
    command: sudo -u hduser ./stop-yarn.sh chdir={{hadoop_home}}/sbin
    when: is_master

  - name: Stop history server
    tags: stop
    command: sudo -u hduser ./mr-jobhistory-daemon.sh stop historyserver chdir={{hadoop_home}}/sbin
    when: is_master
